# important: https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/

default:
  image: docker:20

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:19.03.0-dind

before_script:
  - docker info

stages:
  - build
  - push

Build container image:
  stage: build
  script:
    - docker build -t litecoin .

Push container image:
  stage: push
  script:
    - echo "insert push stage"
