# important: https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/

default:
  image: docker:20

variables:
  DOCKER_DRIVER: overlay2
  # Create the certificates inside this directory for both the server
  # and client. The certificates used by the client will be created in
  # /certs/client so we only need to share this directory with the
  # volume mount in `config.toml`.
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.0-dind
  - echo -n "$DOCKERHUB_TOKEN" | docker login --username flaccid --password-stdin

before_script:
  - docker info

stages:
  - build
  - push

Build container image:
  stage: build
  script:
    - cd container-litecoin
    - docker build -t flaccid/litecoin:0.18.1 .

Push container image:
  stage: push
  script:
    - docker tag flaccid/litecoin:0.18.1 flaccid/litecoin:latest
    - docker push flaccid/litecoin:0.18.1
    - docker push flaccid/litecoin:latest
