# important: https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/

default:
  image: docker:20

variables:
  DOCKER_DRIVER: overlay2
  # Create the certificates inside this directory for both the server
  # and client. The certificates used by the client will be created in
  # /certs/client so we only need to share this directory with the
  # volume mount in `config.toml`.
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.0-dind

before_script:
  - docker info
  - echo -n "$DOCKERHUB_TOKEN" | docker login --username flaccid --password-stdin

stages:
  - build
  - push

# usually we would save the image as an artifact and use it in the push stage
# which could be on a different runner, but for ease, we'll push latest
# and pull it in the push stage to be re-tagged
Build container image:
  stage: build
  script:
    - cd container-litecoin
    - docker build -t flaccid/litecoin:latest .
    - docker push flaccid/litecoin:latest

Push container image:
  stage: push
  script:
    - docker pull flaccid/litecoin:latest
    - docker tag flaccid/litecoin:latest flaccid/litecoin:0.18.1
    - docker push flaccid/litecoin:0.18.1
