apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: litecoin-data
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
